import type { Employee, Role, Blueprint, ActivityEntry, Routine } from './team-types';

// ---------------------------------------------------------------------------
// Employees
// ---------------------------------------------------------------------------

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'owner',
    name: 'You',
    role: 'Business Owner',
    department: 'operations',
    departmentLabel: 'Owner',
    status: 'working',
    trustLevel: 'autonomous',
    reportsTo: null,
    icon: '👤',
    skills: [],
    trainingMaterials: [],
    standingInstructions: '',
    hoursUsed: 0,
    hoursAllocated: 0,
    approvalsCount: 0,
    deliverablesCount: 0,
    hireDate: '2026-01-15',
    isChiefOfStaff: false,
  },
  {
    id: 'cos',
    name: 'Atlas Chief of Staff',
    role: 'Chief of Staff',
    department: 'operations',
    departmentLabel: 'Operations',
    status: 'working',
    trustLevel: 'autonomous',
    reportsTo: 'owner',
    icon: '🧠',
    skills: ['Strategic Planning', 'Team Management', 'Goal Setting'],
    trainingMaterials: ['company-handbook.pdf', 'q1-goals.pdf', 'brand-guidelines.pdf'],
    standingInstructions:
      'Coordinate all AI employees each morning. Prioritize tasks based on weekly goals and flag any blockers to the owner. Summarize team output at end of day.',
    hoursUsed: 30,
    hoursAllocated: 40,
    approvalsCount: 0,
    deliverablesCount: 0,
    hireDate: '2026-02-01',
    isChiefOfStaff: true,
  },
  {
    id: 'smm',
    name: 'Social Media Manager',
    role: 'Social Media Manager',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    status: 'working',
    trustLevel: 'supervised',
    reportsTo: 'cos',
    icon: '📱',
    skills: ['Content Creation', 'Scheduling', 'Analytics'],
    trainingMaterials: ['brand-voice-guide.pdf', 'social-calendar-template.xlsx'],
    standingInstructions:
      'Review social mentions and DMs each morning. Draft posts following the brand voice guide and queue them for approval. Report engagement metrics every Friday.',
    hoursUsed: 12,
    hoursAllocated: 20,
    approvalsCount: 8,
    deliverablesCount: 14,
    hireDate: '2026-02-10',
    isChiefOfStaff: false,
  },
  {
    id: 'em',
    name: 'Email Marketer',
    role: 'Email Marketer',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    status: 'idle',
    trustLevel: 'trusted',
    reportsTo: 'cos',
    icon: '✉️',
    skills: ['Copywriting', 'Campaigns', 'A/B Testing'],
    trainingMaterials: ['email-templates.zip', 'audience-segments.csv', 'past-campaigns-report.pdf'],
    standingInstructions:
      'Monitor campaign open and click rates each morning. Draft new campaigns for upcoming promotions and run A/B tests on subject lines. Escalate any deliverability issues immediately.',
    hoursUsed: 9,
    hoursAllocated: 15,
    approvalsCount: 22,
    deliverablesCount: 28,
    hireDate: '2026-02-14',
    isChiefOfStaff: false,
  },
  {
    id: 'lq',
    name: 'Lead Qualifier',
    role: 'Lead Qualifier',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    status: 'working',
    trustLevel: 'supervised',
    reportsTo: 'cos',
    icon: '🎯',
    skills: ['Lead Scoring', 'Research', 'Routing'],
    trainingMaterials: ['ideal-customer-profile.pdf', 'crm-guide.pdf'],
    standingInstructions:
      'Score all new inbound leads using the ICP criteria every morning. Research the top 5 prospects and add enrichment notes. Route qualified leads to the sales pipeline by end of day.',
    hoursUsed: 18,
    hoursAllocated: 25,
    approvalsCount: 5,
    deliverablesCount: 11,
    hireDate: '2026-02-20',
    isChiefOfStaff: false,
  },
  {
    id: 'bk',
    name: 'Bookkeeper',
    role: 'Bookkeeper',
    department: 'operations',
    departmentLabel: 'Operations',
    status: 'idle',
    trustLevel: 'autonomous',
    reportsTo: 'cos',
    icon: '📒',
    skills: ['Bookkeeping', 'Reports', 'Reconciliation'],
    trainingMaterials: ['chart-of-accounts.pdf', 'reconciliation-checklist.pdf', 'quickbooks-export.csv'],
    standingInstructions:
      'Reconcile all new bank transactions against invoices each morning. Categorize expenses and flag any discrepancies over $500. Generate a weekly financial summary every Friday.',
    hoursUsed: 3,
    hoursAllocated: 10,
    approvalsCount: 45,
    deliverablesCount: 48,
    hireDate: '2026-02-05',
    isChiefOfStaff: false,
  },
  {
    id: 'as',
    name: 'Appointment Scheduler',
    role: 'Appointment Scheduler',
    department: 'operations',
    departmentLabel: 'Operations',
    status: 'working',
    trustLevel: 'trusted',
    reportsTo: 'cos',
    icon: '📅',
    skills: ['Scheduling', 'Reminders', 'Calendar'],
    trainingMaterials: ['scheduling-policy.pdf'],
    standingInstructions:
      'Check for new appointment requests each morning and confirm them within business hours. Send reminders 24 hours before each appointment. Reschedule cancellations and fill open slots when possible.',
    hoursUsed: 11,
    hoursAllocated: 15,
    approvalsCount: 30,
    deliverablesCount: 35,
    hireDate: '2026-03-01',
    isChiefOfStaff: false,
  },
];

// ---------------------------------------------------------------------------
// Roles (hiring catalog)
// ---------------------------------------------------------------------------

export const MOCK_ROLES: Role[] = [
  // Sales & Marketing
  {
    id: 'role-smm',
    name: 'Social Media Manager',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    icon: '📱',
    description: 'Creates and schedules social media posts, monitors engagement, and grows your online audience across platforms.',
    skills: ['Content Creation', 'Scheduling', 'Analytics'],
    estimatedHours: 20,
    responsibilities: [
      'Draft and schedule posts across Instagram, Facebook, LinkedIn, and X',
      'Monitor comments, DMs, and mentions and respond on your behalf',
      'Track follower growth, engagement rates, and top-performing content',
      'Maintain a content calendar aligned with your marketing goals',
      'Report weekly analytics with insights and recommendations',
    ],
    sampleTasks: [
      'Create a week of Instagram posts promoting our new product launch',
      'Write a LinkedIn thought-leadership post about industry trends',
      'Compile this month\'s social media performance report',
      'Draft responses to the 12 unanswered comments from this week',
    ],
  },
  {
    id: 'role-em',
    name: 'Email Marketer',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    icon: '✉️',
    description: 'Writes and sends email campaigns, manages subscriber lists, and runs A/B tests to improve open rates and conversions.',
    skills: ['Copywriting', 'Campaigns', 'A/B Testing'],
    estimatedHours: 15,
    responsibilities: [
      'Write and send email campaigns to your subscriber list',
      'Run A/B tests on subject lines and content',
      'Manage subscriber segments and list hygiene',
      'Track open rates, click rates, and conversions',
      'Create automated welcome and nurture sequences',
    ],
    sampleTasks: [
      'Write a welcome email sequence for new customers',
      'Draft a promotional email for our spring sale',
      'Create a re-engagement campaign for inactive subscribers',
      'A/B test subject lines for this month\'s newsletter',
    ],
  },
  {
    id: 'role-lq',
    name: 'Lead Qualifier',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    icon: '🎯',
    description: 'Scores inbound leads against your ideal customer profile, researches prospects, and routes qualified opportunities to sales.',
    skills: ['Lead Scoring', 'Research', 'Routing'],
    estimatedHours: 25,
    responsibilities: [
      'Score all new inbound leads against your ideal customer profile',
      'Research top prospects and add enrichment data to the CRM',
      'Route qualified leads to the appropriate sales pipeline stage',
      'Flag high-priority opportunities for immediate follow-up',
      'Generate weekly pipeline reports with conversion metrics',
    ],
    sampleTasks: [
      'Score and prioritize the 20 leads that came in overnight',
      'Research Greenfield Corp and prepare a prospect brief',
      'Update CRM records with enrichment data for this week\'s hot leads',
      'Generate a pipeline health report for the Monday sales meeting',
    ],
  },
  {
    id: 'role-cw',
    name: 'Content Writer',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    icon: '✍️',
    description: 'Produces blog posts, landing page copy, and marketing collateral aligned with your brand voice and SEO strategy.',
    skills: ['SEO Writing', 'Blog Posts', 'Brand Voice'],
    estimatedHours: 20,
    responsibilities: [
      'Write SEO-optimized blog posts on topics relevant to your audience',
      'Create landing page copy for campaigns and product launches',
      'Develop marketing collateral like case studies and one-pagers',
      'Maintain a consistent brand voice across all written content',
      'Research keywords and trending topics in your industry',
    ],
    sampleTasks: [
      'Write a 1,200-word blog post on "5 Ways to Reduce Customer Churn"',
      'Draft landing page copy for our new service tier',
      'Create a customer success case study for Acme Corp',
      'Research and outline 4 blog post ideas for next month',
    ],
  },
  {
    id: 'role-fus',
    name: 'Follow-Up Specialist',
    department: 'sales_marketing',
    departmentLabel: 'Sales & Marketing',
    icon: '🔄',
    description: 'Sends timely follow-up messages to prospects and customers, ensuring no opportunity falls through the cracks.',
    skills: ['Follow-Ups', 'CRM Updates', 'Sequences'],
    estimatedHours: 15,
    responsibilities: [
      'Send follow-up emails to prospects who haven\'t responded',
      'Create and manage multi-step follow-up sequences',
      'Update CRM deal stages and next-action dates after each touchpoint',
      'Flag stale deals that need attention or a different approach',
      'Track follow-up response rates and optimize messaging',
    ],
    sampleTasks: [
      'Send a follow-up to all prospects who received a proposal last week',
      'Create a 3-step sequence for post-demo follow-ups',
      'Update CRM records for the 15 deals with no activity in 7 days',
      'Draft a "checking in" email for warm leads that went cold',
    ],
  },
  // Operations
  {
    id: 'role-bk',
    name: 'Bookkeeper',
    department: 'operations',
    departmentLabel: 'Operations',
    icon: '📒',
    description: 'Reconciles bank transactions, categorizes expenses, and generates weekly financial summaries to keep your books clean.',
    skills: ['Bookkeeping', 'Reports', 'Reconciliation'],
    estimatedHours: 10,
    responsibilities: [
      'Reconcile bank transactions against invoices and receipts',
      'Categorize expenses into the correct chart-of-accounts categories',
      'Flag discrepancies or unusual charges for your review',
      'Generate weekly revenue, expense, and cash-flow summaries',
      'Prepare month-end financial reports',
    ],
    sampleTasks: [
      'Reconcile all transactions from the past week',
      'Categorize the 30 uncategorized expenses in the ledger',
      'Generate a profit-and-loss summary for March',
      'Flag any transactions over $500 that don\'t match an invoice',
    ],
  },
  {
    id: 'role-as',
    name: 'Appointment Scheduler',
    department: 'operations',
    departmentLabel: 'Operations',
    icon: '📅',
    description: 'Manages your calendar, books appointments with clients, and sends automated reminders to reduce no-shows.',
    skills: ['Scheduling', 'Reminders', 'Calendar'],
    estimatedHours: 15,
    responsibilities: [
      'Confirm and schedule new appointment requests within business hours',
      'Send 24-hour reminder messages to reduce no-shows',
      'Reschedule cancellations and fill open calendar slots',
      'Coordinate availability across team members for group meetings',
      'Track appointment volume and no-show rates weekly',
    ],
    sampleTasks: [
      'Confirm the 8 appointment requests that came in today',
      'Send reminders for all appointments scheduled tomorrow',
      'Reschedule the 3 cancelled appointments from this week',
      'Find an open 30-minute slot for a client meeting next Tuesday',
    ],
  },
  {
    id: 'role-it',
    name: 'Inventory Tracker',
    department: 'operations',
    departmentLabel: 'Operations',
    icon: '📦',
    description: 'Monitors stock levels, flags low-inventory items, and generates reorder recommendations so you never run out.',
    skills: ['Inventory Counts', 'Reorder Alerts', 'Reporting'],
    estimatedHours: 10,
    responsibilities: [
      'Monitor current stock levels and flag items below reorder thresholds',
      'Generate reorder recommendations with suggested quantities',
      'Track inventory turnover rates and identify slow-moving items',
      'Reconcile physical counts against system records',
      'Produce weekly inventory status reports',
    ],
    sampleTasks: [
      'Check which items are below their reorder point and create a reorder list',
      'Generate an inventory turnover report for the past 30 days',
      'Identify the top 5 slow-moving SKUs and recommend action',
      'Reconcile this week\'s shipment receipts against purchase orders',
    ],
  },
  // Customer Service
  {
    id: 'role-csr',
    name: 'Customer Service Rep',
    department: 'customer_service',
    departmentLabel: 'Customer Service',
    icon: '💬',
    description: 'Responds to customer inquiries, resolves common issues, and escalates complex cases to the appropriate team member.',
    skills: ['Ticket Resolution', 'FAQ Handling', 'Escalation'],
    estimatedHours: 25,
    responsibilities: [
      'Respond to incoming support tickets and customer messages',
      'Resolve common issues using your knowledge base and FAQ',
      'Escalate complex or sensitive cases to the right team member',
      'Track ticket volume, resolution time, and satisfaction scores',
      'Update the FAQ and knowledge base with new solutions',
    ],
    sampleTasks: [
      'Respond to the 15 open support tickets in the queue',
      'Draft a reply for the billing dispute from customer #4821',
      'Update the FAQ with answers for the 3 most common questions this week',
      'Compile a customer support summary for this week\'s team meeting',
    ],
  },
  {
    id: 'role-rm',
    name: 'Review Manager',
    department: 'customer_service',
    departmentLabel: 'Customer Service',
    icon: '⭐',
    description: 'Monitors online reviews, drafts professional responses, and identifies trends in customer feedback.',
    skills: ['Review Responses', 'Sentiment Analysis', 'Reputation'],
    estimatedHours: 10,
    responsibilities: [
      'Monitor new reviews across Google, Yelp, and industry platforms',
      'Draft professional, on-brand responses to both positive and negative reviews',
      'Identify recurring themes and sentiment trends in customer feedback',
      'Flag urgent negative reviews that need immediate attention',
      'Report weekly on review volume, average rating, and sentiment shifts',
    ],
    sampleTasks: [
      'Respond to the 6 new Google reviews from this week',
      'Draft a thoughtful reply to the 1-star review about shipping delays',
      'Compile a sentiment analysis of all reviews from the past month',
      'Identify the top 3 complaints mentioned in recent negative reviews',
    ],
  },
  {
    id: 'role-cfu',
    name: 'Client Follow-Up',
    department: 'customer_service',
    departmentLabel: 'Customer Service',
    icon: '🤝',
    description: 'Reaches out to past clients for feedback, upsell opportunities, and relationship nurturing to boost retention.',
    skills: ['Check-Ins', 'Satisfaction Surveys', 'Upselling'],
    estimatedHours: 15,
    responsibilities: [
      'Send check-in messages to clients after service delivery',
      'Distribute satisfaction surveys and compile the results',
      'Identify upsell and cross-sell opportunities based on client history',
      'Nurture relationships with personalized touchpoints on milestones',
      'Track client retention metrics and flag at-risk accounts',
    ],
    sampleTasks: [
      'Send a 30-day check-in email to clients who completed onboarding last month',
      'Distribute a satisfaction survey to all Q1 clients',
      'Identify 5 existing clients who might benefit from our new premium tier',
      'Draft a personalized anniversary message for our top 10 clients',
    ],
  },
];

// ---------------------------------------------------------------------------
// Blueprints
// ---------------------------------------------------------------------------

export const MOCK_BLUEPRINTS: Blueprint[] = [
  {
    id: 'bp-dental',
    name: 'Dental Office',
    icon: '🦷',
    industry: 'Healthcare / Dental',
    teamSize: 5,
    roles: ['Appointment Scheduler', 'Customer Service Rep', 'Review Manager', 'Follow-Up Specialist', 'Bookkeeper'],
    description:
      'A ready-made team for dental practices. Handles appointment booking, patient follow-ups, online review management, and bookkeeping so you can focus on patient care.',
  },
  {
    id: 'bp-realestate',
    name: 'Real Estate Agency',
    icon: '🏠',
    industry: 'Real Estate',
    teamSize: 4,
    roles: ['Lead Qualifier', 'Follow-Up Specialist', 'Social Media Manager', 'Appointment Scheduler'],
    description:
      'Built for real estate agents and brokerages. Qualifies inbound leads, nurtures prospects with timely follow-ups, and keeps your social presence active between showings.',
  },
  {
    id: 'bp-roofing',
    name: 'Roofing Company',
    icon: '🏗️',
    industry: 'Home Services / Roofing',
    teamSize: 3,
    roles: ['Lead Qualifier', 'Appointment Scheduler', 'Client Follow-Up'],
    description:
      'Designed for roofing and home service contractors. Scores storm-damage leads, books estimates, and follows up after jobs to earn reviews and referrals.',
  },
  {
    id: 'bp-restaurant',
    name: 'Restaurant',
    icon: '🍽️',
    industry: 'Food & Beverage',
    teamSize: 4,
    roles: ['Social Media Manager', 'Review Manager', 'Inventory Tracker', 'Customer Service Rep'],
    description:
      'Tailored for restaurants and cafes. Keeps your social feeds fresh with daily specials, responds to reviews, tracks inventory, and handles customer inquiries.',
  },
  {
    id: 'bp-agency',
    name: 'Marketing Agency',
    icon: '📣',
    industry: 'Marketing & Advertising',
    teamSize: 5,
    roles: ['Content Writer', 'Social Media Manager', 'Email Marketer', 'Lead Qualifier', 'Bookkeeper'],
    description:
      'An AI team for marketing agencies. Produces client content, manages social accounts, runs email campaigns, qualifies new business leads, and keeps finances organized.',
  },
];

// ---------------------------------------------------------------------------
// Activity feed
// ---------------------------------------------------------------------------

export const MOCK_ACTIVITY: ActivityEntry[] = [
  {
    id: 'act-1',
    employeeId: 'smm',
    employeeName: 'Social Media Manager',
    employeeIcon: '📱',
    action: 'Drafted Instagram post',
    detail: 'Created carousel post highlighting spring promotions with 5 slides and captions.',
    timestamp: '2026-03-31T09:15:00Z',
    needsApproval: true,
    approved: null,
    status: 'success',
    deliverablePreview:
      '🌸 Spring is here and so are our biggest deals! Swipe through to see what\'s new this season. Slide 1: "Fresh Starts, Fresh Savings" — 20% off all services…',
  },
  {
    id: 'act-2',
    employeeId: 'smm',
    employeeName: 'Social Media Manager',
    employeeIcon: '📱',
    action: 'Published engagement report',
    detail: 'Weekly engagement report: +12% followers, 340 interactions, top post reached 2.1k impressions.',
    timestamp: '2026-03-28T16:30:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-3',
    employeeId: 'em',
    employeeName: 'Email Marketer',
    employeeIcon: '✉️',
    action: 'Sent April newsletter',
    detail: 'Delivered "April Updates" campaign to 2,480 subscribers. Open rate: 38.2%, CTR: 5.7%.',
    timestamp: '2026-03-30T10:00:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-4',
    employeeId: 'em',
    employeeName: 'Email Marketer',
    employeeIcon: '✉️',
    action: 'Completed A/B test',
    detail: 'Subject line test finished: "Don\'t miss out" (42% open) beat "Your April perks" (31% open). Winner applied to remaining sends.',
    timestamp: '2026-03-29T14:20:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-5',
    employeeId: 'lq',
    employeeName: 'Lead Qualifier',
    employeeIcon: '🎯',
    action: 'Scored 14 new leads',
    detail: 'Processed overnight form submissions. 3 marked hot, 7 warm, 4 cold. Hot leads routed to sales pipeline.',
    timestamp: '2026-03-31T08:05:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-6',
    employeeId: 'lq',
    employeeName: 'Lead Qualifier',
    employeeIcon: '🎯',
    action: 'Drafted prospect research brief',
    detail: 'Deep-dive on Greenfield Corp — $2M revenue, 45 employees, expanding to new markets. Strong ICP fit.',
    timestamp: '2026-03-31T13:45:00Z',
    needsApproval: true,
    approved: null,
    status: 'success',
    deliverablePreview:
      'Greenfield Corp Overview: Founded 2019, HQ Austin TX. Revenue ~$2M ARR, 45 FTE. Currently expanding into Southeast region. Key contact: Dana Reeves, VP Growth. ICP score: 92/100…',
  },
  {
    id: 'act-7',
    employeeId: 'bk',
    employeeName: 'Bookkeeper',
    employeeIcon: '📒',
    action: 'Reconciled 47 transactions',
    detail: 'All bank transactions from Mar 24–28 matched against invoices. No discrepancies found.',
    timestamp: '2026-03-28T10:30:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-8',
    employeeId: 'bk',
    employeeName: 'Bookkeeper',
    employeeIcon: '📒',
    action: 'Generated weekly financial summary',
    detail: 'Week of Mar 24: Revenue $18,420, Expenses $7,230, Net $11,190. Cash flow positive.',
    timestamp: '2026-03-28T15:00:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-9',
    employeeId: 'as',
    employeeName: 'Appointment Scheduler',
    employeeIcon: '📅',
    action: 'Booked 6 appointments',
    detail: 'Confirmed 6 new client meetings for this week. Sent calendar invites and 24-hour reminders.',
    timestamp: '2026-03-30T09:00:00Z',
    needsApproval: false,
    approved: null,
    status: 'success',
  },
  {
    id: 'act-10',
    employeeId: 'smm',
    employeeName: 'Social Media Manager',
    employeeIcon: '📱',
    action: 'Drafted Twitter thread',
    detail: 'Five-tweet thread on industry trends with data points and a CTA linking to the blog.',
    timestamp: '2026-03-31T11:30:00Z',
    needsApproval: true,
    approved: null,
    status: 'success',
    deliverablePreview:
      '🧵 1/5 The landscape is shifting fast — here are 3 trends every small business owner should watch this quarter. Thread 👇\n\n2/5 Trend #1: AI-powered customer service is no longer optional…',
  },
];

// ---------------------------------------------------------------------------
// Routines
// ---------------------------------------------------------------------------

export const MOCK_ROUTINES: Routine[] = [
  {
    id: 'rt-smm-1',
    employeeId: 'smm',
    name: 'Check social mentions',
    description: 'Review all new mentions, comments, and DMs across platforms and respond or flag as needed.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '09:00',
    enabled: true,
  },
  {
    id: 'rt-smm-2',
    employeeId: 'smm',
    name: 'Create and post content',
    description: 'Draft, design, and queue social posts for the next 24 hours based on the content calendar.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '14:00',
    enabled: true,
  },
  {
    id: 'rt-smm-3',
    employeeId: 'smm',
    name: 'Weekly analytics report',
    description: 'Compile follower growth, engagement rates, and top-performing posts into a weekly summary.',
    days: ['fri'],
    time: '16:00',
    enabled: true,
  },
  {
    id: 'rt-em-1',
    employeeId: 'em',
    name: 'Check campaign performance',
    description: 'Review open rates, click rates, and unsubscribes for all active email campaigns.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '09:30',
    enabled: true,
  },
  {
    id: 'rt-em-2',
    employeeId: 'em',
    name: 'Send scheduled campaigns',
    description: 'Finalize and send pre-approved email campaigns to their target audience segments.',
    days: ['tue', 'thu'],
    time: '10:00',
    enabled: true,
  },
  {
    id: 'rt-lq-1',
    employeeId: 'lq',
    name: 'Score new leads',
    description: 'Evaluate all new inbound leads against the ideal customer profile and assign priority scores.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '08:00',
    enabled: true,
  },
  {
    id: 'rt-lq-2',
    employeeId: 'lq',
    name: 'Research top prospects',
    description: 'Deep-dive on the highest-scored leads: company size, revenue, decision-makers, and recent news.',
    days: ['mon', 'wed', 'fri'],
    time: '13:00',
    enabled: true,
  },
  {
    id: 'rt-bk-1',
    employeeId: 'bk',
    name: 'Reconcile transactions',
    description: 'Match new bank transactions against invoices and receipts, flag any discrepancies.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '10:00',
    enabled: true,
  },
  {
    id: 'rt-bk-2',
    employeeId: 'bk',
    name: 'Generate weekly summary',
    description: 'Produce a revenue, expenses, and cash-flow summary for the past week.',
    days: ['fri'],
    time: '15:00',
    enabled: true,
  },
  {
    id: 'rt-as-1',
    employeeId: 'as',
    name: 'Check appointment requests',
    description: 'Review and confirm new appointment requests, resolving any scheduling conflicts.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '08:30',
    enabled: true,
  },
  {
    id: 'rt-as-2',
    employeeId: 'as',
    name: 'Send daily reminders',
    description: 'Send 24-hour reminder messages to all clients with appointments the following day.',
    days: ['mon', 'tue', 'wed', 'thu', 'fri'],
    time: '07:00',
    enabled: true,
  },
];
