import { nanoid } from 'nanoid';
import { eq, and, or } from 'drizzle-orm';
import { db } from '../db/connection';
import {
  people,
  companies,
  deals,
  meetings,
  documents,
  decisions,
  relationships,
} from '../db/schema';

// --- ID Generators ---

function personId(): string {
  return `ppl_${nanoid(8)}`;
}

function companyId(): string {
  return `cmp_${nanoid(8)}`;
}

function dealId(): string {
  return `deal_${nanoid(8)}`;
}

function meetingId(): string {
  return `mtg_${nanoid(8)}`;
}

function documentId(): string {
  return `doc_${nanoid(8)}`;
}

function decisionId(): string {
  return `dec_${nanoid(8)}`;
}

// --- Types ---

export interface CreatePersonInput {
  name: string;
  email?: string;
  phone?: string;
  companyId?: string;
  role?: string;
  slackUserId?: string;
  source?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateCompanyInput {
  name: string;
  industry?: string;
  status?: string;
  revenue?: number;
  employeeCount?: number;
  website?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateDealInput {
  companyId: string;
  name: string;
  stage?: string;
  value?: number;
  closeDate?: number;
  ownerId?: string;
  ownerSlackId?: string;
  source?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateMeetingInput {
  title: string;
  date?: number;
  duration?: number;
  source?: string;
  zoomMeetingId?: string;
  calendarEventId?: string;
  transcriptText?: string;
  summary?: string;
  meetingType?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateDocumentInput {
  title: string;
  type?: string;
  content?: string;
  version?: number;
  autoGenerated?: boolean;
  status?: string;
  createdBy?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateDecisionInput {
  what: string;
  context?: string;
  decidedBy?: string;
  meetingId?: string;
  sourceType?: string;
  sourceRef?: string;
  metadata?: Record<string, unknown>;
}

// --- CRUD: People ---

export function createPerson(input: CreatePersonInput) {
  const now = Math.floor(Date.now() / 1000);
  const id = personId();
  db.insert(people).values({
    id,
    name: input.name,
    email: input.email ?? null,
    phone: input.phone ?? null,
    companyId: input.companyId ?? null,
    role: input.role ?? null,
    slackUserId: input.slackUserId ?? null,
    source: input.source ?? 'manual',
    metadata: input.metadata ?? null,
    createdAt: now,
    updatedAt: now,
  }).run();
  return db.select().from(people).where(eq(people.id, id)).get()!;
}

// --- CRUD: Companies ---

export function createCompany(input: CreateCompanyInput) {
  const now = Math.floor(Date.now() / 1000);
  const id = companyId();
  db.insert(companies).values({
    id,
    name: input.name,
    industry: input.industry ?? null,
    status: input.status ?? 'prospect',
    revenue: input.revenue ?? null,
    employeeCount: input.employeeCount ?? null,
    website: input.website ?? null,
    metadata: input.metadata ?? null,
    createdAt: now,
    updatedAt: now,
  }).run();
  return db.select().from(companies).where(eq(companies.id, id)).get()!;
}

// --- CRUD: Deals ---

export function createDeal(input: CreateDealInput) {
  const now = Math.floor(Date.now() / 1000);
  const id = dealId();
  db.insert(deals).values({
    id,
    companyId: input.companyId,
    name: input.name,
    stage: input.stage ?? 'lead',
    value: input.value ?? null,
    closeDate: input.closeDate ?? null,
    ownerId: input.ownerId ?? null,
    ownerSlackId: input.ownerSlackId ?? null,
    source: input.source ?? null,
    metadata: input.metadata ?? null,
    createdAt: now,
    updatedAt: now,
  }).run();
  return db.select().from(deals).where(eq(deals.id, id)).get()!;
}

// --- CRUD: Meetings ---

export function createMeeting(input: CreateMeetingInput) {
  const now = Math.floor(Date.now() / 1000);
  const id = meetingId();
  db.insert(meetings).values({
    id,
    title: input.title,
    date: input.date ?? null,
    duration: input.duration ?? null,
    source: input.source ?? 'zoom',
    zoomMeetingId: input.zoomMeetingId ?? null,
    calendarEventId: input.calendarEventId ?? null,
    transcriptText: input.transcriptText ?? null,
    summary: input.summary ?? null,
    meetingType: input.meetingType ?? null,
    metadata: input.metadata ?? null,
    createdAt: now,
    updatedAt: now,
  }).run();
  return db.select().from(meetings).where(eq(meetings.id, id)).get()!;
}

// --- CRUD: Documents ---

export function createDocument(input: CreateDocumentInput) {
  const now = Math.floor(Date.now() / 1000);
  const id = documentId();
  db.insert(documents).values({
    id,
    title: input.title,
    type: input.type ?? null,
    content: input.content ?? null,
    version: input.version ?? 1,
    autoGenerated: input.autoGenerated ?? false,
    status: input.status ?? 'draft',
    createdBy: input.createdBy ?? null,
    metadata: input.metadata ?? null,
    createdAt: now,
    updatedAt: now,
  }).run();
  return db.select().from(documents).where(eq(documents.id, id)).get()!;
}

// --- CRUD: Decisions ---

export function createDecision(input: CreateDecisionInput) {
  const now = Math.floor(Date.now() / 1000);
  const id = decisionId();
  db.insert(decisions).values({
    id,
    what: input.what,
    context: input.context ?? null,
    decidedBy: input.decidedBy ?? null,
    meetingId: input.meetingId ?? null,
    sourceType: input.sourceType ?? 'meeting',
    sourceRef: input.sourceRef ?? null,
    metadata: input.metadata ?? null,
    createdAt: now,
  }).run();
  return db.select().from(decisions).where(eq(decisions.id, id)).get()!;
}

// --- Finders ---

export function findPersonBySlackId(slackUserId: string) {
  return db.select().from(people).where(eq(people.slackUserId, slackUserId)).get() ?? null;
}

export function findPersonByEmail(email: string) {
  return db.select().from(people).where(eq(people.email, email)).get() ?? null;
}

export function findPersonByName(name: string) {
  return db.select().from(people).where(eq(people.name, name)).get() ?? null;
}

export function findCompanyByName(name: string) {
  return db.select().from(companies).where(eq(companies.name, name)).get() ?? null;
}

export function findMeetingByZoomId(zoomMeetingId: string) {
  return db.select().from(meetings).where(eq(meetings.zoomMeetingId, zoomMeetingId)).get() ?? null;
}

// --- findOrCreate helpers ---

export function findOrCreatePerson(input: CreatePersonInput) {
  // Try slackUserId first
  if (input.slackUserId) {
    const existing = findPersonBySlackId(input.slackUserId);
    if (existing) return existing;
  }

  // Try email
  if (input.email) {
    const existing = findPersonByEmail(input.email);
    if (existing) return existing;
  }

  // Try exact name match
  if (input.name) {
    const existing = findPersonByName(input.name);
    if (existing) return existing;
  }

  // Create new
  return createPerson(input);
}

export function findOrCreateCompany(input: CreateCompanyInput) {
  const existing = findCompanyByName(input.name);
  if (existing) return existing;
  return createCompany(input);
}

// --- Relationship management ---

export function linkEntities(
  sourceType: string,
  sourceId: string,
  targetType: string,
  targetId: string,
  relationshipType: string,
  metadata?: Record<string, unknown>,
) {
  // Prevent duplicates
  const existing = db.select().from(relationships).where(
    and(
      eq(relationships.sourceType, sourceType),
      eq(relationships.sourceId, sourceId),
      eq(relationships.targetType, targetType),
      eq(relationships.targetId, targetId),
      eq(relationships.relationshipType, relationshipType),
    )
  ).get();

  if (existing) return existing;

  const now = Math.floor(Date.now() / 1000);
  db.insert(relationships).values({
    sourceType,
    sourceId,
    targetType,
    targetId,
    relationshipType,
    metadata: metadata ?? null,
    createdAt: now,
  }).run();

  return db.select().from(relationships).where(
    and(
      eq(relationships.sourceType, sourceType),
      eq(relationships.sourceId, sourceId),
      eq(relationships.targetType, targetType),
      eq(relationships.targetId, targetId),
      eq(relationships.relationshipType, relationshipType),
    )
  ).get()!;
}

export function getRelatedEntities(
  entityType: string,
  entityId: string,
  relType?: string,
) {
  const outgoingConditions = relType
    ? and(
        eq(relationships.sourceType, entityType),
        eq(relationships.sourceId, entityId),
        eq(relationships.relationshipType, relType),
      )
    : and(
        eq(relationships.sourceType, entityType),
        eq(relationships.sourceId, entityId),
      );

  const incomingConditions = relType
    ? and(
        eq(relationships.targetType, entityType),
        eq(relationships.targetId, entityId),
        eq(relationships.relationshipType, relType),
      )
    : and(
        eq(relationships.targetType, entityType),
        eq(relationships.targetId, entityId),
      );

  const outgoing = db.select().from(relationships).where(outgoingConditions!).all();
  const incoming = db.select().from(relationships).where(incomingConditions!).all();

  return { outgoing, incoming };
}
