import { eq, and } from 'drizzle-orm';
import { semanticSearch, KnowledgeSearchResult } from './embedding-service';
import { recordQA } from './feedback-service';
import { anthropic } from '../ai/client';
import { db } from '../db/connection';
import { documents } from '../db/schema';

// --- Types ---

export interface KnowledgeBotQuery {
  question: string;
  askedBy?: string;
  askedVia?: string;
}

export interface KnowledgeBotResponse {
  answer: string;
  confidence: 'high' | 'medium' | 'low';
  sourceCount: number;
  qaId: number;
  sources: KnowledgeSearchResult[];
}

// --- SOP-aware question detection ---

const PROCESS_KEYWORDS = [
  'process', 'how do we', 'procedure', 'sop', 'workflow', 'how should we',
  'steps to', 'step by step', 'what is the process', 'what are the steps',
  'how to', 'policy', 'guidelines', 'protocol',
];

function isProcessQuestion(question: string): boolean {
  const lower = question.toLowerCase();
  return PROCESS_KEYWORDS.some((kw) => lower.includes(kw));
}

// --- Active SOPs ---

interface ActiveSOP {
  id: string;
  title: string;
  content: string | null;
}

function getActiveSOPs(): ActiveSOP[] {
  return db
    .select({ id: documents.id, title: documents.title, content: documents.content })
    .from(documents)
    .where(and(eq(documents.status, 'active'), eq(documents.autoGenerated, false)))
    .all()
    .concat(
      db
        .select({ id: documents.id, title: documents.title, content: documents.content })
        .from(documents)
        .where(and(eq(documents.status, 'active'), eq(documents.autoGenerated, true)))
        .all()
    );
}

// --- Main query function ---

export async function queryKnowledgeBot(input: KnowledgeBotQuery): Promise<KnowledgeBotResponse> {
  const { question, askedBy, askedVia } = input;

  // 1. Semantic search — 12 results, filter similarity > 0.25
  const allResults = await semanticSearch(question, 12);
  const results = allResults.filter((r) => r.similarity > 0.25);

  // 2. SOP-aware: include active SOPs for process questions
  let sopContext = '';
  if (isProcessQuestion(question)) {
    const activeSOPs = getActiveSOPs();
    if (activeSOPs.length > 0) {
      const sopLines = activeSOPs
        .filter((s) => s.content)
        .slice(0, 3)
        .map((s, i) => `[SOP ${i + 1}: ${s.title}]\n${s.content}`)
        .join('\n\n');
      if (sopLines) {
        sopContext = `\n\nActive SOPs for reference:\n${sopLines}`;
      }
    }
  }

  // 3. Build context for Claude
  const contextBlocks = results
    .map((r, i) => `[Source ${i + 1}] (${r.sourceType}): ${r.content}`)
    .join('\n\n');

  const fullContext = results.length > 0
    ? `Knowledge base results:\n${contextBlocks}${sopContext}`
    : sopContext
      ? `No matching knowledge base entries found.${sopContext}`
      : '';

  // 4. Synthesize answer with Claude
  let answer: string;
  try {
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1024,
      system: [
        'You are Atlas Chief of Staff, an AI assistant for a fast-moving executive team.',
        'Answer questions directly and concisely. Executives need answers, not essays.',
        'Cite sources as [Source N] when referencing knowledge base entries.',
        'If the provided context does not contain enough information to answer, say so clearly — do not fabricate.',
        'If sources conflict, note the conflict briefly.',
        'Keep answers tight: bullet points over paragraphs when listing items.',
      ].join(' '),
      messages: [
        {
          role: 'user',
          content: fullContext
            ? `Context:\n${fullContext}\n\nQuestion: ${question}`
            : `Question: ${question}\n\n(No relevant knowledge base entries found for this question.)`,
        },
      ],
    });

    const textBlock = response.content.find((b) => b.type === 'text');
    answer = textBlock?.type === 'text' ? textBlock.text : 'Unable to generate answer.';
  } catch (err) {
    console.error('[knowledge-bot] Claude synthesis error:', err);
    throw err;
  }

  // 5. Calculate confidence based on top similarity scores
  const topSim = results.length > 0 ? results[0].similarity : 0;
  let confidence: 'high' | 'medium' | 'low';
  if (topSim >= 0.7) {
    confidence = 'high';
  } else if (topSim >= 0.45) {
    confidence = 'medium';
  } else {
    confidence = 'low';
  }

  // 6. Record Q&A
  const qaId = recordQA({
    question,
    answer,
    confidence,
    sourceEntryIds: results.map((r) => r.id),
    askedBy: askedBy ?? undefined,
    askedVia: askedVia ?? undefined,
  });

  // 7. Return response with top 5 sources
  return {
    answer,
    confidence,
    sourceCount: results.length,
    qaId,
    sources: results.slice(0, 5),
  };
}
