import { eq } from 'drizzle-orm';
import { db } from '../db/connection';
import { documents } from '../db/schema';
import { semanticSearch, ingestText } from './embedding-service';
import { createDocument, linkEntities } from './graph-service';
import { generateSOP, checkSOPUpdate } from '../ai/sop-generator';
import { markSOPGenerated } from './topic-tracker';

const SOP_SEARCH_LIMIT = 15;

// --- Types ---

export interface CreateSOPResult {
  docId: string;
  title: string;
  format: string;
  summary: string;
}

export interface CreateSOPOptions {
  topicId?: number;
  createdBy?: string;
}

// --- Create SOP for a Topic ---

export async function createSOPForTopic(
  topic: string,
  options: CreateSOPOptions = {},
): Promise<CreateSOPResult | null> {
  console.log(`[sop-service] Creating SOP for topic: "${topic}"`);

  // Semantic search for relevant knowledge entries
  let searchResults;
  try {
    searchResults = await semanticSearch(topic, SOP_SEARCH_LIMIT);
  } catch (err) {
    console.error('[sop-service] Semantic search failed:', err);
    return null;
  }

  if (searchResults.length === 0) {
    console.warn(`[sop-service] No knowledge entries found for topic: "${topic}"`);
    return null;
  }

  const excerpts = searchResults.map((r) => r.content);

  // Generate SOP via Claude
  const generated = await generateSOP(topic, excerpts);
  if (!generated) {
    console.error('[sop-service] SOP generation failed');
    return null;
  }

  // Persist as a document
  const doc = createDocument({
    title: generated.title,
    type: 'sop',
    content: generated.content,
    autoGenerated: true,
    status: 'draft',
    createdBy: options.createdBy ?? 'system',
    metadata: {
      topic,
      format: generated.format,
      summary: generated.summary,
      confidence: generated.confidence,
    },
  });

  const docId = doc.id;

  // Embed the SOP content for future semantic retrieval
  try {
    await ingestText({
      sourceType: 'sop',
      sourceId: docId,
      text: `${generated.title}\n\n${generated.content}`,
      metadata: { topic, format: generated.format },
    });
  } catch (err) {
    console.error('[sop-service] Error embedding SOP:', err);
  }

  // Mark the topic as having a generated SOP
  if (options.topicId !== undefined) {
    markSOPGenerated(options.topicId, docId);
  }

  console.log(`[sop-service] SOP created: ${docId} ("${generated.title}")`);

  return {
    docId,
    title: generated.title,
    format: generated.format,
    summary: generated.summary,
  };
}

// --- Review SOP for Updates ---

export async function reviewSOPForUpdates(docId: string): Promise<boolean> {
  console.log(`[sop-service] Reviewing SOP for updates: ${docId}`);

  const currentDoc = db
    .select()
    .from(documents)
    .where(eq(documents.id, docId))
    .get();

  if (!currentDoc) {
    console.error(`[sop-service] Document not found: ${docId}`);
    return false;
  }

  if (!currentDoc.content) {
    console.warn(`[sop-service] Document has no content: ${docId}`);
    return false;
  }

  // Derive topic from metadata or title
  const metadata = currentDoc.metadata as Record<string, unknown> | null;
  const topic = (metadata?.topic as string) ?? currentDoc.title;

  // Search for new content since the SOP was created
  let searchResults;
  try {
    searchResults = await semanticSearch(topic, SOP_SEARCH_LIMIT);
  } catch (err) {
    console.error('[sop-service] Semantic search failed during review:', err);
    return false;
  }

  if (searchResults.length === 0) {
    console.log('[sop-service] No relevant content found for update check');
    return false;
  }

  const newExcerpts = searchResults.map((r) => r.content);

  // Check if an update is warranted
  const updateResult = await checkSOPUpdate(currentDoc.content, newExcerpts);
  if (!updateResult) {
    console.error('[sop-service] SOP update check failed');
    return false;
  }

  if (!updateResult.needsUpdate) {
    console.log(`[sop-service] SOP ${docId} is up to date: ${updateResult.reason}`);
    return false;
  }

  console.log(`[sop-service] SOP ${docId} needs update: ${updateResult.reason}`);

  // Create a new version document
  const currentVersion = currentDoc.version ?? 1;
  const newDoc = createDocument({
    title: currentDoc.title,
    type: 'sop',
    content: updateResult.updatedContent ?? currentDoc.content,
    version: currentVersion + 1,
    autoGenerated: true,
    status: 'draft',
    createdBy: 'system',
    metadata: {
      ...(metadata ?? {}),
      changesSummary: updateResult.changesSummary,
      previousVersion: docId,
    },
  });

  // Link old → new as 'superseded_by'
  linkEntities('document', docId, 'document', newDoc.id, 'superseded_by');

  // Archive the old SOP
  const now = Math.floor(Date.now() / 1000);
  db.update(documents)
    .set({ status: 'archived', updatedAt: now })
    .where(eq(documents.id, docId))
    .run();

  // Embed new SOP content
  try {
    await ingestText({
      sourceType: 'sop',
      sourceId: newDoc.id,
      text: `${newDoc.title}\n\n${newDoc.content}`,
      metadata: { topic, format: metadata?.format as string | undefined },
    });
  } catch (err) {
    console.error('[sop-service] Error embedding updated SOP:', err);
  }

  console.log(`[sop-service] New SOP version created: ${newDoc.id}`);
  return true;
}

// --- Query SOPs ---

export function getSOPs(status?: string): Array<typeof documents.$inferSelect> {
  const allDocs = db.select().from(documents).where(eq(documents.type, 'sop')).all();

  if (!status) return allDocs;
  return allDocs.filter((d) => d.status === status);
}

// --- Publish SOP ---

export function publishSOP(docId: string): void {
  const now = Math.floor(Date.now() / 1000);
  db.update(documents)
    .set({ status: 'active', updatedAt: now })
    .where(eq(documents.id, docId))
    .run();
  console.log(`[sop-service] Published SOP: ${docId}`);
}

// --- Archive SOP ---

export function archiveSOP(docId: string): void {
  const now = Math.floor(Date.now() / 1000);
  db.update(documents)
    .set({ status: 'archived', updatedAt: now })
    .where(eq(documents.id, docId))
    .run();
  console.log(`[sop-service] Archived SOP: ${docId}`);
}
