import { sqliteTable, text, integer, index, blob } from 'drizzle-orm/sqlite-core';

export const people = sqliteTable('people', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email'),
  phone: text('phone'),
  companyId: text('company_id'),
  role: text('role'),
  slackUserId: text('slack_user_id'),
  source: text('source').notNull().default('manual'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
  updatedAt: integer('updated_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_people_email').on(table.email),
  index('idx_people_slack_user_id').on(table.slackUserId),
  index('idx_people_company_id').on(table.companyId),
]);

export const companies = sqliteTable('companies', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  industry: text('industry'),
  status: text('status').notNull().default('prospect'),
  revenue: integer('revenue'),
  employeeCount: integer('employee_count'),
  website: text('website'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
  updatedAt: integer('updated_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_companies_name').on(table.name),
  index('idx_companies_status').on(table.status),
]);

export const deals = sqliteTable('deals', {
  id: text('id').primaryKey(),
  companyId: text('company_id').notNull(),
  name: text('name').notNull(),
  stage: text('stage').notNull().default('lead'),
  value: integer('value'),
  closeDate: integer('close_date'),
  ownerId: text('owner_id'),
  ownerSlackId: text('owner_slack_id'),
  source: text('source'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
  updatedAt: integer('updated_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_deals_company_id').on(table.companyId),
  index('idx_deals_stage').on(table.stage),
  index('idx_deals_owner_slack_id').on(table.ownerSlackId),
]);

export const meetings = sqliteTable('meetings', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  date: integer('date'),
  duration: integer('duration'),
  source: text('source').notNull().default('zoom'),
  zoomMeetingId: text('zoom_meeting_id'),
  calendarEventId: text('calendar_event_id'),
  transcriptText: text('transcript_text'),
  summary: text('summary'),
  meetingType: text('meeting_type'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
  updatedAt: integer('updated_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_meetings_zoom_meeting_id').on(table.zoomMeetingId),
  index('idx_meetings_date').on(table.date),
]);

export const documents = sqliteTable('documents', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  type: text('type'),
  content: text('content'),
  version: integer('version').notNull().default(1),
  autoGenerated: integer('auto_generated', { mode: 'boolean' }).notNull().default(false),
  status: text('status').notNull().default('draft'),
  createdBy: text('created_by'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
  updatedAt: integer('updated_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_documents_type').on(table.type),
  index('idx_documents_status').on(table.status),
]);

export const decisions = sqliteTable('decisions', {
  id: text('id').primaryKey(),
  what: text('what').notNull(),
  context: text('context'),
  decidedBy: text('decided_by'),
  meetingId: text('meeting_id'),
  sourceType: text('source_type').notNull().default('meeting'),
  sourceRef: text('source_ref'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_decisions_meeting_id').on(table.meetingId),
  index('idx_decisions_decided_by').on(table.decidedBy),
]);

export const relationships = sqliteTable('relationships', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
  targetType: text('target_type').notNull(),
  targetId: text('target_id').notNull(),
  relationshipType: text('relationship_type').notNull(),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_relationships_source').on(table.sourceType, table.sourceId),
  index('idx_relationships_target').on(table.targetType, table.targetId),
  index('idx_relationships_type').on(table.relationshipType),
]);

export const knowledgeEntries = sqliteTable('knowledge_entries', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  sourceType: text('source_type').notNull(),
  sourceId: text('source_id').notNull(),
  content: text('content').notNull(),
  embedding: blob('embedding'),
  embeddingModel: text('embedding_model'),
  metadata: text('metadata', { mode: 'json' }),
  createdAt: integer('created_at').notNull().$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_knowledge_entries_source').on(table.sourceType, table.sourceId),
]);

// ─── Topic Counts (Pattern Detection) ─────────────────────
export const topicCounts = sqliteTable('topic_counts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  topic: text('topic').notNull(),
  normalizedTopic: text('normalized_topic').notNull(),
  occurrences: integer('occurrences').notNull().default(1),
  sourceTypes: text('source_types', { mode: 'json' }),
  sourceIds: text('source_ids', { mode: 'json' }),
  lastSeenAt: integer('last_seen_at').$defaultFn(() => Math.floor(Date.now() / 1000)),
  sopGenerated: integer('sop_generated', { mode: 'boolean' }).default(false),
  sopId: text('sop_id'),
  createdAt: integer('created_at').$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_topic_counts_normalized').on(table.normalizedTopic),
  index('idx_topic_counts_occurrences').on(table.occurrences),
]);

// ─── Q&A Interactions (Self-Learning Feedback Loop) ───────
export const qaInteractions = sqliteTable('qa_interactions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  question: text('question').notNull(),
  answer: text('answer').notNull(),
  wasCorrect: integer('was_correct', { mode: 'boolean' }),
  correction: text('correction'),
  confidence: text('confidence'),
  sourceEntryIds: text('source_entry_ids', { mode: 'json' }),
  askedBy: text('asked_by'),
  askedVia: text('asked_via'),
  createdAt: integer('created_at').$defaultFn(() => Math.floor(Date.now() / 1000)),
}, (table) => [
  index('idx_qa_asked_by').on(table.askedBy),
  index('idx_qa_was_correct').on(table.wasCorrect),
]);
